version: '3.9'

services:
  db:
    build:
      context: ./db
    ports:
      - 3306:3306
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.2.0
    restart: always
    ports:
      - 8000:80
    links:
      - db
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
      - PMA_ARBITRARY=1
    depends_on:
      - db

  web:
    build:
      context: ./web
    restart: always
    env_file:
      - .env
    environment:
      - DBHOST=db
      - DBUSER=code
      - DBPASS=maze
      - DBSCHEMA=codemaze
    links:
      - db
    ports:
      - 5003:80
    depends_on:
      - db

# Do not tamper this!
  flag_manager:
    build:
      context: ./flag_manager
    restart: always
    links:
      - db
    env_file:
      - .env
    environment:
      - DBHOST=db
      - DBUSER=code
      - DBPASS=maze
      - DBSCHEMA=codemaze
    ports:
      - 9002:9002
    depends_on:
      - db